<h2 class="centerText">Forgot your Password?</h2>

<?php if (count($this->messages) ) : ?>
<div class="centerText <?php echo $this->flashMessengerClass; ?>">
<?php foreach ($this->messages as $message) : ?>
    <p><?php echo $this->escape($message); ?></p>
<?php endforeach; ?>
</div>
<?php endif; ?>

<div style="width: 220px; margin-left: auto; margin-right: auto;">
<form action="<?php echo $this->url(array('controller' => 'login', 'action' => $this->url(array(),'forgot-password-process'))); ?>" method="post">
		<fieldset id="loginForm">
            
            <label for="email">Enter your email address<input id="email" name="email" type="text" size="30" value="" /></label>
            
            <input name="submit" name="submit" type="submit" value="Submit"/>
		</fieldset>
</form>
</div>