<h2>Resend Activation Email</h2>

<p>Enter your email address below and we'll re-send your activation email. If you still don't receive it after an hour please double check it's not being caught by your spam filters, then email help@practicalplants.org for assistance.</p>

<?php if (count($this->messages) ) : ?>
<div class="<?php echo $this->flashMessengerClass; ?>">
<?php foreach ($this->messages as $message) : ?>
    <p><?php echo $this->escape($message); ?></p>
<?php endforeach; ?>
</div>
<?php endif; ?>

<?php echo $this->form ?>